# Generated by Django 5.2.1 on 2025-05-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('KASIR', 'Kasir'), ('DAPUR', 'Dapur'), ('MANAJER', 'Manajer')], max_length=15),
        ),
    ]
