# Generated by Django 5.2.1 on 2025-05-27 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(unique=True)),
                ('total_pesanan', models.PositiveIntegerField(default=0)),
                ('total_pendapatan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_item_terjual', models.PositiveIntegerField(default=0)),
                ('rata_rata_per_pesanan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Laporan Harian',
                'verbose_name_plural': 'Laporan Harian',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.AddField(
            model_name='meja',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.CreateModel(
            name='MenuAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jumlah_terjual', models.PositiveIntegerField(default=0)),
                ('total_pendapatan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Analytics Menu',
                'verbose_name_plural': 'Analytics Menu',
                'ordering': ['-tanggal', '-jumlah_terjual'],
                'unique_together': {('menu_item', 'tanggal')},
            },
        ),
    ]
