# Generated by Django 5.2.1 on 2025-05-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dailyreport_meja_qr_code_menuanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='analytics_processed',
            field=models.BooleanField(default=False),
        ),
    ]
