# Generated by Django 5.2.1 on 2025-05-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_pesanan_analytics_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='nama_pemesan',
            field=models.CharField(default='Pelanggan', max_length=100),
        ),
    ]
